FROM php:8.0.5

RUN docker-php-ext-install pdo pdo_mysql sockets

RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . /app

RUN composer install

RUN php artisan key:generate
# RUN php artisan migrate --force

CMD php artisan serve --host=0.0.0.0 --port=8050
EXPOSE 8050
