name: Deployment

on:
  push:
    branches: [master]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ranielevan/projeto-leitura:latest

  pull-and-execute-instance:
    needs: build-and-run
    runs-on: agent-runner

    steps:
      - name: Show running containers
        run: sudo docker ps

      - name: Pull the image
        run: sudo docker pull ranielevan/projeto-leitura:latest

      # - name: Stop active instance
      #   run: sudo docker stop projeto_leitura_instance

      # - name: Remove stopped DefaultInstance
      #   run: sudo docker container prune -f

      - name: Run new instance
        run: sudo docker run -it -p 8000:80 -d --name projeto_leitura_instance ranielevan/projeto-leitura:latest

      # - name: Copy frontend config files
      #   run: sudo docker cp "/home/ubuntu/default.conf" projeto_leitura_instance:"/etc/nginx/conf.d"

      # - name: Restart container
      #   run: sudo docker restart projeto_leitura_instance

      # - name: Finished! Show running containers
      #   run: sudo docker ps

      # - name: Remove old images
      #   run: sudo docker image prune -f
